[package]
name = "changen"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Intuitive, good-defaults changelog generation."
repository = "https://github.com/Froloket64/changen"

[dependencies]
git2 = "0.20.2"
peeking-iter = "0.3.0"
